application: pyzh
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: themes/default/images
  
- url: /stylesheets
  static_dir: themes/default/stylesheets
  
- url: /javascript
  static_dir: themes/default/javascript
  
- url: /fckeditor
  static_dir: static/fckeditor

- url: /syntaxhighlighter
  static_dir: static/syntaxhighlighter
  
- url: /admins/.*
  #script: admin/main.py
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

#- url: /install/.*
#  script: install.py
#  login: admin

- url: /.*
  script: main.py