application: pyzh
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
#- url: /admin/.*
  #script: admin/main.py
  #script: $PYTHON_LIB/google/appengine/ext/admin
  #login: admin

#- url: /install/.*
#  script: install.py
#  login: admin

- url: /test
  script: test.py

- url: /.*
  script: /blog/main.py